### ISSUE TITLE
Removes Applescript Package after Install

### ISSUE THREAD

**Issue by DrLulz** [idleberg/AppleScript-Sublime-Text#3]
I'm installing via Package Control. After install I'm not able to select applescript as language. Is this intended?

For anyone else not wanting this behavior backup `/Library/Application Support/Sublime Text 3` before install. 

OSX 10.10.2
Sublime (3065)

**Comment by idleberg** [comment]
Hm, that's funny. The moment I remove this package, I can select AppleScript as source, but after a few seconds I an error. I should have a second look at this when I get home.

I'm not sure whether I used the package myself since I upgraded to 10.10, though I don't think this is related.

**Comment by idleberg** [comment]
I think this is a simple name conflict. As a quick solution you can do the following:

    cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
    git clone https://github.com/idleberg/AppleScript-Sublime-Text

Before I work on solving this issue permanently, I will speak to the Package Control developers to see if their update to 3.0 might have caused this.

**Comment by i8degrees** [comment]
Hi,

I just bumped into this same issue -- syntax highlighting for AppleScript vanishes -- and can confirm that it does appear to be a name conflict on my system, too.

```console
cd ~/Library/Application\ Support/Sublime\ Text\ 3/Installed Packages
mv AppleScript.sublime-package AppleScript-for-SublimeText.sublime-package
```

I also noticed that I was unable to list or remove the package from the command palette until after renaming the package file.

Cheers,
Jeff

**Comment by idleberg** [comment]
Okay. This is indeed a name conflict and there will be a patch for Package Control sometime in the future. In the meantime here is what you can do:

1. Delete the AppleScript package in `~/Library/Application\ Support/Sublime\ Text\ 3/Installed Packages`
2. Remove the AppleScript package from the user settings ("Preferences: Package Control Settings - User" in your command palette)
3. Install via Git as described above

The Package Control developers like to do some more testing before releasing their patch. Before that there appears to be no alternative to the steps described above, I'm very sorry about that!

**Comment by i8degrees** [comment]
Thanks! I followed your directions, shutdown and re-opened Sublime Text (just to be safe) and all is well.

Cheers,
Jeff

**Comment by Chris-May** [comment]
Thanks for the directions! Seems as though the Package Control guys haven't updated yet.
To the best of your knowledge, will we have to reinstall this through Package Control for it to handle updates?

**Comment by idleberg** [comment]
@Chris-May I'm afraid you will have to reinstall

**Comment by Chris-May** [comment]
Not a big deal. Thanks again for your help!

**Comment by idleberg** [comment]
According to the Package Control developers, it should be working now. Works okay for me in Sublime Text 3.

**Comment by i8degrees** [comment]
I removed the cloned repository from my ST User directory, reinstalled the package and all is well for me, too (Sublime Text 3)! Thanks! :-D

Cheers,
Jeff
